In [4]:

from transformers import BertTokenizer, BertModel
import torch

In [64]:
from transformers import BertTokenizer, BertModel
import torch
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained("bert-base-uncased")
text = "red cat is meowing"
encoded_input = tokenizer(text, return_tensors='pt')
output1 = model(**encoded_input).last_hidden_state
text = "math lesson"
encoded_input = tokenizer(text, return_tensors='pt')
output2 = model(**encoded_input).last_hidden_state


In [65]:
output2[0].shape

torch.Size([4, 768])

In [66]:
output1 = torch.nn.functional.normalize(output1[0])
output2 = torch.nn.functional.normalize(output2[0])

In [67]:
(output1[0] @ output2[0].T)

tensor(0.9294, grad_fn=<DotBackward0>)

In [69]:
!pip install sentence_transformers

  Using cached scipy-1.13.1-cp39-cp39-win_amd64.whl.metadata (60 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 11.0/11.0 MB 76.9 MB/s eta 0:00:00
Using cached scipy-1.13.1-cp39-cp39-win_amd64.whl (46.2 MB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)


In [43]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('stsb-roberta-large')

c:\Users\giord\miniconda3\envs\weightedCL\lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:13: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm, trange
c:\Users\giord\miniconda3\envs\weightedCL\lib\site-packages\transformers\tokenization_utils_base.py:1617: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [78]:
text = "red cat is meowing"
embeddings1 = model.encode(['a man picking out a vehicle from the trailer', 'a web animation of a businessman', 'a video showing footage from sporting events', 'three men talking about their youtube channel and thanking their viewers', 'advertisement of seat basket', 'a video of a young man in a white shirt inviting his colleagues to join him', 'some peole are sitting in hall', 'a group discusses a man s outfit', 'a man is singing on stage to a huge audience he is holding a microphone', 'all persons are wearing bikini dresses and playing in sea', 'few barbie dolls are playing one doll puts shoe to other barbie these are used to play by a kid', 'a man prepares some food in the kitchen', 'several women in pink outfits and various other styles are standing and smiling', 'a lady describes about workout and exercises for women', 'a compilation of vine videos is shown', 'a lady talks into a megaphone'] , convert_to_tensor=True)
text = "red dog is barking"
embeddings2 = model.encode(text , convert_to_tensor=True)

In [79]:
embeddings1.shape

torch.Size([16, 1024])

In [51]:
embeddings1 = torch.nn.functional.normalize(embeddings1,dim=0)
print(embeddings1.shape)
embeddings2 = torch.nn.functional.normalize(embeddings2,dim=0)
embeddings1 @ embeddings2.T

torch.Size([2, 1024])


tensor([6.8731, 6.8731], device='cuda:0')

In [1]:
!pip install pillow

In [34]:
from PIL import Image
import os

def create_gif(image_folder, output_gif, duration=100):
    """
    Crea una GIF animata a partire da una cartella di immagini PNG.

    Args:
    - image_folder (str): La cartella che contiene le immagini PNG.
    - output_gif (str): Il percorso del file di output GIF.
    - duration (int): La durata di ogni frame in millisecondi (default: 100ms).
    """
    # Recupera tutte le immagini PNG dalla cartella specificata
    images = []
    def sort_files_by_modification_time(folder_path):
        # Get all files in the specified folder
        files = [os.path.join(folder_path, f) for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]
    
        # Sort files based on modification time
        files.sort(key=lambda x: os.path.getmtime(x))
    
        return files
    
    for filename in sort_files_by_modification_time(image_folder):#os.listdir(image_folder):
        if filename.endswith(".png"):
            img_path = os.path.join(image_folder, filename)
            print(img_path)
            img = Image.open(img_path)
            images.append(img)
    
    # Verifica che ci siano immagini da combinare
    if not images:
        raise ValueError("Non sono state trovate immagini PNG nella cartella specificata.")

    # Salva le immagini come GIF animata
    images[0].save(
        output_gif,
        save_all=True,
        append_images=images[1:],  # Immagini da aggiungere alla GIF
        duration=duration,  # Durata di ogni frame
        loop=0  # Numero di loop (0 per loop infinito)
    )

    print(f"GIF animata creata: {output_gif}")




# Esempio di utilizzo
create_gif("C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA", "C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA/output.gif", duration=100)


C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 0.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 50.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 100.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 150.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 200.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 250.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 300.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 350.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 400.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 450.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLo

In [107]:
import torch
def compute_centroidsTest(text_embeddings, visual_embeddings, audio_embeddings):
    """
    Computes the centroid for each pair of samples between text embeddings and visual/audio embeddings
    by calculating the mean of the corresponding feature vectors across the two modalities.

    Parameters:
    - text_embeddings (torch.Tensor): Tensor of shape (batch_size1, feature_dim) representing text embeddings.
    - visual_audio_embeddings (torch.Tensor): Tensor of shape (batch_size2, feature_dim) representing visual/audio embeddings.

    Returns:
    - torch.Tensor: Tensor of shape (batch_size1, batch_size2, feature_dim) representing the centroid for each pair.
    """

    # Get batch sizes
    batch_size1 = text_embeddings.shape[0]   # For text embeddings
    batch_size2 = visual_embeddings.shape[0]  # For visual/audio embeddings

    # Compute centroids by averaging text and visual/audio embeddings
    # Expand the dimensions to allow pairwise computation
    text_expanded = text_embeddings.unsqueeze(1)  # Shape: [batch_size1, 1, feature_dim]
    print(text_expanded.shape)
    print(text_expanded)
    visual_expanded = visual_embeddings.unsqueeze(0)  # Shape: [1, batch_size2, feature_dim]
    print(visual_expanded.shape)
    print(visual_expanded)
    audio_expanded = audio_embeddings.unsqueeze(0)

    # Compute the centroid by averaging the embeddings
    
    centroids = (text_expanded + visual_expanded + audio_expanded) / 3.0
    #print(centroids)
    print(centroids)

    
    centroid_norms = torch.norm(centroids, dim=-1)

    #norm_condition = centroid_norms >= 0.5
    #centroid_norms = torch.where(norm_condition, centroid_norms, torch.tensor(0.0))

    return centroid_norms, centroids


In [108]:
a=torch.tensor([[0,1,1],[0,0,1]])
b=torch.tensor([[0,1,0],[1,0,1]])
c=torch.tensor([[0,0,1],[1,1,1]])

matrix_norm,centroids=compute_centroidsTest(a,b,c)
print(matrix_norm)
print(matrix_norm.T)

torch.Size([2, 1, 3])
tensor([[[0, 1, 1]],

        [[0, 0, 1]]])
torch.Size([1, 2, 3])
tensor([[[0, 1, 0],
         [1, 0, 1]]])
tensor([[[0.0000, 0.6667, 0.6667],
         [0.6667, 0.6667, 1.0000]],

        [[0.0000, 0.3333, 0.6667],
         [0.6667, 0.3333, 1.0000]]])
tensor([[0.9428, 1.3744],
        [0.7454, 1.2472]])
tensor([[0.9428, 0.7454],
        [1.3744, 1.2472]])


In [112]:
centroids.shape

torch.Size([2, 2, 3])

In [111]:
print(centroids[0]@centroids[0].T)

tensor([[0.8889, 1.1111],
        [1.1111, 1.8889]])


In [42]:
matrix_norm.sort(dim=-1,descending=True)

torch.return_types.sort(
values=tensor([[1.3744, 0.9428],
        [1.2472, 0.7454]]),
indices=tensor([[1, 0],
        [1, 0]]))

In [76]:
import torch.nn.functional as F

a = torch.tensor([1,-1,-1]).float()
target = torch.tensor([1,0,0]).float()
F.cross_entropy(a, target, label_smoothing=0.1)

tensor(0.3729)

In [15]:
import torch

# Create a sample matrix of shape [n, n]
n = 5
matrix = torch.randn(n, n)

# Print the original matrix
print("Original Matrix:")
print(matrix)

# Remove the diagonal
# Create an index tensor for the rows and columns
mask = torch.ones((n, n), dtype=torch.bool)  # Create a boolean mask of shape [n, n]
mask.fill_diagonal_(False)                   # Set the diagonal to False

# Use the mask to index the original matrix
# Get only the non-diagonal elements
non_diag_elements = matrix[mask].view(n , n-1 )

# Print the new matrix
print("\nNew Matrix without Diagonal:")
print(non_diag_elements)


Original Matrix:
tensor([[-1.3026,  0.3969,  0.6831, -0.4572, -0.4039],
        [-0.4150, -0.9352,  0.1681, -0.1742, -1.1731],
        [ 1.3658, -0.4777,  0.2989, -0.8788, -1.5159],
        [ 0.1417,  0.8148,  1.0215, -0.2499,  0.9693],
        [ 0.7999, -0.2600,  0.1153, -1.0073, -0.8122]])

New Matrix without Diagonal:
tensor([[ 0.3969,  0.6831, -0.4572, -0.4039],
        [-0.4150,  0.1681, -0.1742, -1.1731],
        [ 1.3658, -0.4777, -0.8788, -1.5159],
        [ 0.1417,  0.8148,  1.0215,  0.9693],
        [ 0.7999, -0.2600,  0.1153, -1.0073]])


In [99]:
import numpy as np
def compute_similarity_matrix():
    # Define the number of items
    n_items = 10

    # Initialize an empty similarity matrix
    similarity_matrix = np.zeros((n_items, n_items))

    # Define the two groups
    group_1 = [0, 1, 2, 3, 4]  # Group 1 (0-4)
    group_2 = [5, 6, 7, 8, 9]  # Group 2 (5-9)

    # Fill the matrix with similarity values
    for i in range(n_items):
        for j in range(i, n_items):
            if i == j:
                similarity_matrix[i, j] = 1  # Perfect similarity with itself
            elif (i in group_1 and j in group_1) or (i in group_2 and j in group_2):
                similarity_matrix[i, j] = 0.8  # High similarity within the same group
            else:
                similarity_matrix[i, j] = 0  # Low similarity between groups

            similarity_matrix[j, i] = similarity_matrix[i, j]  # Ensure symmetry

    # Convert to torch tensor and move to GPU
    similarity_matrix = torch.tensor(similarity_matrix).to('cuda')

    # Print the raw similarity matrix
    print("Raw Similarity Matrix:")
    print(similarity_matrix)

    # If smoothing with sigmoid style
    #similarity_matrix = 1 - (1 / (1 + torch.exp(-5 * (similarity_matrix))))  # Smoothing to get values between 0 and 1
    #similarity_matrix = (1 / (1 + torch.exp(-5 * (similarity_matrix))))
    print("Smoothing Applied (Sigmoid Style):")
    print(similarity_matrix)

    # If linear decaying (if needed, you can uncomment this line)
    # similarity_matrix = 1 - similarity_matrix

    return similarity_matrix

In [100]:
similarity_matrix = compute_similarity_matrix()

Raw Similarity Matrix:
tensor([[1.0000, 0.8000, 0.8000, 0.8000, 0.8000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.8000, 1.0000, 0.8000, 0.8000, 0.8000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.8000, 0.8000, 1.0000, 0.8000, 0.8000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.8000, 0.8000, 0.8000, 1.0000, 0.8000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.8000, 0.8000, 0.8000, 0.8000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.8000, 0.8000, 0.8000,
         0.8000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.8000, 1.0000, 0.8000, 0.8000,
         0.8000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.8000, 0.8000, 1.0000, 0.8000,
         0.8000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.8000, 0.8000, 0.8000, 1.0000,
         0.8000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.8000, 0.8000, 0.8000, 0.8000,
     

In [101]:
import torch.nn.functional as F

F.softmax(similarity_matrix,dim=0)

tensor([[0.1636, 0.1339, 0.1339, 0.1339, 0.1339, 0.0602, 0.0602, 0.0602, 0.0602,
         0.0602],
        [0.1339, 0.1636, 0.1339, 0.1339, 0.1339, 0.0602, 0.0602, 0.0602, 0.0602,
         0.0602],
        [0.1339, 0.1339, 0.1636, 0.1339, 0.1339, 0.0602, 0.0602, 0.0602, 0.0602,
         0.0602],
        [0.1339, 0.1339, 0.1339, 0.1636, 0.1339, 0.0602, 0.0602, 0.0602, 0.0602,
         0.0602],
        [0.1339, 0.1339, 0.1339, 0.1339, 0.1636, 0.0602, 0.0602, 0.0602, 0.0602,
         0.0602],
        [0.0602, 0.0602, 0.0602, 0.0602, 0.0602, 0.1636, 0.1339, 0.1339, 0.1339,
         0.1339],
        [0.0602, 0.0602, 0.0602, 0.0602, 0.0602, 0.1339, 0.1636, 0.1339, 0.1339,
         0.1339],
        [0.0602, 0.0602, 0.0602, 0.0602, 0.0602, 0.1339, 0.1339, 0.1636, 0.1339,
         0.1339],
        [0.0602, 0.0602, 0.0602, 0.0602, 0.0602, 0.1339, 0.1339, 0.1339, 0.1636,
         0.1339],
        [0.0602, 0.0602, 0.0602, 0.0602, 0.0602, 0.1339, 0.1339, 0.1339, 0.1339,
         0.1636]], device='c

In [102]:
similarity_matrix = similarity_matrix / 0.1
F.softmax(similarity_matrix,dim=0)

tensor([[6.4869e-01, 8.7791e-02, 8.7791e-02, 8.7791e-02, 8.7791e-02, 2.9450e-05,
         2.9450e-05, 2.9450e-05, 2.9450e-05, 2.9450e-05],
        [8.7791e-02, 6.4869e-01, 8.7791e-02, 8.7791e-02, 8.7791e-02, 2.9450e-05,
         2.9450e-05, 2.9450e-05, 2.9450e-05, 2.9450e-05],
        [8.7791e-02, 8.7791e-02, 6.4869e-01, 8.7791e-02, 8.7791e-02, 2.9450e-05,
         2.9450e-05, 2.9450e-05, 2.9450e-05, 2.9450e-05],
        [8.7791e-02, 8.7791e-02, 8.7791e-02, 6.4869e-01, 8.7791e-02, 2.9450e-05,
         2.9450e-05, 2.9450e-05, 2.9450e-05, 2.9450e-05],
        [8.7791e-02, 8.7791e-02, 8.7791e-02, 8.7791e-02, 6.4869e-01, 2.9450e-05,
         2.9450e-05, 2.9450e-05, 2.9450e-05, 2.9450e-05],
        [2.9450e-05, 2.9450e-05, 2.9450e-05, 2.9450e-05, 2.9450e-05, 6.4869e-01,
         8.7791e-02, 8.7791e-02, 8.7791e-02, 8.7791e-02],
        [2.9450e-05, 2.9450e-05, 2.9450e-05, 2.9450e-05, 2.9450e-05, 8.7791e-02,
         6.4869e-01, 8.7791e-02, 8.7791e-02, 8.7791e-02],
        [2.9450e-05, 2.9450